language: python
python: '3.9'
node_js: 10.16.3
before_install:
- npm install dredd@14.0.0 --global
- pipenv install --dev
before_script:
- uvicorn todo.server:server &
script:
- dredd oas.yaml http://127.0.0.1:8000 --hookfiles=./hooks.py --language=python
- schemathesis run oas.yaml --base-url=http://localhost:8000 --stateful=links
deploy:
  provider: heroku
  api_key:
    secure: v+fG3vR1hMuOyNI6OQKSh8DwqXu9krE/WrstsbwIW8Im8Ol4fOT5i/tieBuz+NX9kYujkhEu7ZutWmxZhk0jKyDUEZ6EypNfzSGj51IbtfwQciMc3dg5BdorTx3tlTfq4n6axDWZdyH1yZUqlxElpRSvuSO48h1+0xInA8NUyYzBWlND2G7XpONer+cbVgw++/t+Yk/eg5vUOkxEPUIqsuVATiaVP4noleaR4WTMFmdi7AXxH3baq1r3k1GkCPHnequb1Ityj83dJFOyQiP6JlEtpmvSEnln8mEjYWPWbMebEhK2FOz8lyUPAPZJ7Pj1VJeLjEdGN42vlm5mtPSKPyplzkh64xTS0IwdljjjUcm21J0Akj8VaToqw6Q9BN8GBxkR7Abdggq/SVdIeXKsLpgcHN6umcrJum0Kz2DgogqlgPbiAVbta/GGYv2I+QRN6MJ3YV0ERhIiKGbq5vtiBXcuK+WraxdPM20Fg55hi9yI6vH9A30MH5BfjAxRsU4ve1NwUUdwzjCdsj5zUvHFJrpjCl39WHd96R+jJKIkWj7JoAK+l6kTPW7fXX3IDDmj3M9CGjkhoOMF6F7TvQzalzbwBiO96N3QHhhylCxXhNfBbbJCulksZpc0d3LLgJlLdCrSR/SOzY4/2m494EHnjp9+h7cHQWJMMOLUxIw408Y=
  app:
    master: very-simple-todo-api
